config/routes.rb
ContactForm::Application.routes.draw do
  root "home#index"

  resources "contacts", only: [:new, :create]

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :contact_method, :validate => true
  attribute :message
  # attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. 
  def headers
    {
      :subject => "A new Contact",
      :to      => "adam0964@gmail.com",
      :from    => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    begin
      @contact = Contact.new(params[:contact])
      @contact.request = request
      if @contact.deliver
        flash.now[:error]  = nil
        flash.now[:notice] = nil
      else
        flash.now[:error]  = 'Unable to send message.'
        render :new
      end
    rescue ScriptError 
        flash[:error] = "Spam alert!."
    end 
   
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/create.html.haml
.container
  %span
  %h3 #{@contact.name.split.each{|i| i.capitalize!}.join(' ')}, we have received your message. 
  %br
  %br
  = image_tag 'hand.png', :size => '128x128'
  %br
  %br
  %br
  %p Thank you and we'll get back to you within the next 24 business hours.
  %br
  %hr

app/views/contacts/new.html.haml
.container
  %h2 Get in touch
  = simple_form_for @contact, :html => {:class => 'well span10' } do |f|
    = f.input :name,  :required => true, :autofocus => true
    = f.input :email, :required => true
    = f.label :contact_method
    = f.select :contact_method, options_for_select(["Select one", "iPhone", "iPad", "Universal"]), :required => true
    %br
    %br
    = f.input :message, :as => :text, :required => false, :input_html => {:id => "message", :class => "input-xlarge span7", :rows => "10"}
    = f.button :submit, 'Send message', :class => 'btn btn-primary'

app/views/home/index.html.haml
.container
  .row
    .span12
      %h1 Welcome to our home page,
      %br
      %p which doesn't show much yet.
      %br
    .img2 
      = image_tag 'home.png', :size => '250x250'

app/views/layouts/_header.html.haml
.container
  - flash.each do |name, msg|
    - if msg.is_a?(String)
      %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
        %a.close{"data-dismiss" => "alert"}
          &times;
        = content_tag :div, msg, :id => "flash_#{name}"
  .navbar.navbar-fixed-top
    .navbar-inner
      .container
        .nav-collapse.collapse
          %ul.nav
            %li
              = link_to t('home'), root_url
            %li
              = link_to t('contact'), new_contact_path  

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Contact
    = csrf_meta_tags
  %body
    = yield
    = render :partial => 'layouts/header'  

    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true